export const TEMP_ID = -1;

export const State = {
  NOT_LOADED: "NOT_LOADED",
  LOADING: "LOADING",
  LOADED: "LOADED",
  CREATING: "CREATING"
};

export const LoginState = {
  INITIALIZING: "INITIALIZING",
  LOGGED_OUT: "LOGGED_OUT",
  LOGGING_IN: "LOGGING_IN",
  LOGGED_IN: "LOGGED_IN",
  REGISTERING: "REGISTERING",
  LOGGING_OUT: "LOGGING_OUT"
}

export const SequenceState = {
  NOT_LOADED: "NOT_LOADED",
  LOADING: "LOADING",
}