export const TEMP_ID = -1;

export const STATE = {
  NOT_LOADED: 'NOT_LOADED',
  LOADING: 'LOADING',
  LOADED: 'LOADED',
  CREATING: 'CREATING',
};

export const LOGIN_STATE = {
  INITIALIZING: 'INITIALIZING',
  LOGGED_OUT: 'LOGGED_OUT',
  LOGGING_IN: 'LOGGING_IN',
  LOGGED_IN: 'LOGGED_IN',
  REGISTERING: 'REGISTERING',
  LOGGING_OUT: 'LOGGING_OUT',
};
