export const TEMP_ID = -1;

export const State = {
  NOT_LOADED: 0,
  LOADING: 1,
  LOADED: 2,
  CREATING: 3
};

export const LoginState = {
  INITIALIZING: "INITIALIZING",
  LOGGED_OUT: "LOGGED_OUT",
  LOGGING_IN: "LOGGING_IN",
  LOGGED_IN: "LOGGED_IN",
  REGISTERING: "REGISTERING",
  LOGGING_OUT: "LOGGING_OUT"
}
