version: '3.4'

services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile.postgres.dev
    command: postgres -c log_statement=all
    ports:
      - 5432
  api:
    build:
      context: .
      target: dev-env
    command: ./bin/wait-for-postgres.sh db pipenv run flask run --host=0.0.0.0 --port=9000
    tty: true
    stdin_open: true
    environment:
      FLASK_ENV: development
      POSTGRES_USER: postgres
    ports:
      - "9000:9000"
    depends_on:
      - db
