[default]
SQLALCHEMY_DATABASE_URI="" # Setting this to avoid warnings
DB_USER="postgres"
DB_PASSWORD=""
DB_HOST="db"
DB_NAME="human_factor"
SQLALCHEMY_TRACK_MODIFICATIONS="False"
VIDEO_BUCKET="dev.videos.thehumanfactor.ai"

[development]
DB_HOST="db"

[testing]

[staging]
DB_HOST="human-api-db-postgresql.staging.svc.cluster.local"
VIDEO_BUCKET="staging.videos.thehumanfactor.ai"

[production]
VIDEO_BUCKET="prod.videos.thehumanfactor.ai"
